#header
header:
  title: 포트폴리오

#profile_info
profile_info:
  ko_name: 송은지
  us_name: Song Eunji
  ko_blog: 블로그
  ko_github: 깃헙
  ko_email: 이메일
  us_blog: Blog
  us_github: GitHub
  us_email: Email

#footer
footer:
  created_when: © 2022